// AUTO-GENERATED by scripts/gen-images.mjs — do not edit by hand.
// Keyed by the original /images/<group>/<name>.jpg path. Regenerate with:
//   npm run images

export const IMG = {
  "/images/board/bitrus-b-nabasu.jpg": {
    "w": 1000,
    "h": 1250,
    "lqip": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAADwBACdASoYAB4APu1qq0+ppiOiMBgIATAdiWkAy2mLQG+116uZJdiUI96P8UIVAAAA/vC6Ql22YJxvqhx1y3WdMxLvrSr7rrd+JfLmZBBpOqvQ4SbwWamLws+youRPlTi0mwh09dWoYW2zHu/JjT/GVmkKrs4iOQ21AAAA",
    "webp": "/images/board/bitrus-b-nabasu-420.webp 420w, /images/board/bitrus-b-nabasu-768.webp 768w, /images/board/bitrus-b-nabasu-1000.webp 1000w",
    "jpg": "/images/board/bitrus-b-nabasu-420.jpg 420w, /images/board/bitrus-b-nabasu-768.jpg 768w, /images/board/bitrus-b-nabasu-1000.jpg 1000w",
    "fallback": "/images/board/bitrus-b-nabasu-1000.jpg"
  },
  "/images/board/jeffersen-nabasu.jpg": {
    "w": 1000,
    "h": 1250,
    "lqip": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAACQBACdASoYAB4APuVepk2pJSOiMAwBIByJaQDKtYty32uZASR+L/XTGQva+AAA/vC5y5LuJyPwlpZns76AAczY27FsfXXGMlTDey+RlILOigw72ejI7Aqdlcly5rHP5iqs3SuHarenQC0cAAA=",
    "webp": "/images/board/jeffersen-nabasu-420.webp 420w, /images/board/jeffersen-nabasu-768.webp 768w, /images/board/jeffersen-nabasu-1000.webp 1000w",
    "jpg": "/images/board/jeffersen-nabasu-420.jpg 420w, /images/board/jeffersen-nabasu-768.jpg 768w, /images/board/jeffersen-nabasu-1000.jpg 1000w",
    "fallback": "/images/board/jeffersen-nabasu-1000.jpg"
  },
  "/images/board/jerry-nabasu.jpg": {
    "w": 1000,
    "h": 1250,
    "lqip": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAACQBACdASoYAB4APuVepk2pJSOiMAwBIByJaQDKtYty32uZASR+L/XTGQva+AAA/vC5y5LuJyPwlpZns76AAczY27FsfXXGMlTDey+RlILOigw72ejI7Aqdlcly5rHP5iqs3SuHarenQC0cAAA=",
    "webp": "/images/board/jerry-nabasu-420.webp 420w, /images/board/jerry-nabasu-768.webp 768w, /images/board/jerry-nabasu-1000.webp 1000w",
    "jpg": "/images/board/jerry-nabasu-420.jpg 420w, /images/board/jerry-nabasu-768.jpg 768w, /images/board/jerry-nabasu-1000.jpg 1000w",
    "fallback": "/images/board/jerry-nabasu-1000.jpg"
  },
  "/images/board/jibrin-victor-nabasu.jpg": {
    "w": 1000,
    "h": 1250,
    "lqip": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAACQBACdASoYAB4APuVepk2pJSOiMAwBIByJaQDKtYty32uZASR+L/XTGQva+AAA/vC5y5LuJyPwlpZns76AAczY27FsfXXGMlTDey+RlILOigw72ejI7Aqdlcly5rHP5iqs3SuHarenQC0cAAA=",
    "webp": "/images/board/jibrin-victor-nabasu-420.webp 420w, /images/board/jibrin-victor-nabasu-768.webp 768w, /images/board/jibrin-victor-nabasu-1000.webp 1000w",
    "jpg": "/images/board/jibrin-victor-nabasu-420.jpg 420w, /images/board/jibrin-victor-nabasu-768.jpg 768w, /images/board/jibrin-victor-nabasu-1000.jpg 1000w",
    "fallback": "/images/board/jibrin-victor-nabasu-1000.jpg"
  },
  "/images/board/victoria-nabasu.jpg": {
    "w": 1000,
    "h": 1250,
    "lqip": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADQBACdASoYAB4APu1qrlAppiQiqAqpMB2JaQDGBfwIvAL/WVqsqQz5kekkYdgAAAD+8LpLItuSMenHHDzvrYbFR7mcIOGObAjI/WeBT8nFzaDh4jrG6MAU+YbTOtMg8uir38V1Bdco41ZbUMU8zaDnj1URKAAA",
    "webp": "/images/board/victoria-nabasu-420.webp 420w, /images/board/victoria-nabasu-768.webp 768w, /images/board/victoria-nabasu-1000.webp 1000w",
    "jpg": "/images/board/victoria-nabasu-420.jpg 420w, /images/board/victoria-nabasu-768.jpg 768w, /images/board/victoria-nabasu-1000.jpg 1000w",
    "fallback": "/images/board/victoria-nabasu-1000.jpg"
  },
  "/images/group/hero.jpg": {
    "w": 5472,
    "h": 3648,
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACQAwCdASoYABAAPu1qrU8ppiQiMAgBMB2JQAALfi0k+5TImiKAAP7w00qXOeKuHbYkTX6b+UYfDxcn3HsvvdwNKIYK0RmzJGeZZmERwvoDwAAA",
    "webp": "/images/group/hero-640.webp 640w, /images/group/hero-1024.webp 1024w, /images/group/hero-1440.webp 1440w, /images/group/hero-2000.webp 2000w",
    "jpg": "/images/group/hero-640.jpg 640w, /images/group/hero-1024.jpg 1024w, /images/group/hero-1440.jpg 1440w, /images/group/hero-2000.jpg 2000w",
    "fallback": "/images/group/hero-1024.jpg"
  },
  "/images/group/statement.jpg": {
    "w": 5782,
    "h": 3855,
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADwAwCdASoYABAAPu1iqU2ppaOiMAgBMB2JZQDCgCHgEfa5Jy2B4+uAAP7wvU8DowWXKC/6zrGJ3WcLElPs+m9Vn5ujGu9ed4j90dhpuWy7qIHRBer9/XV6uY3aJPbYu7WgZwqqaiwAAA==",
    "webp": "/images/group/statement-640.webp 640w, /images/group/statement-1024.webp 1024w, /images/group/statement-1440.webp 1440w, /images/group/statement-2000.webp 2000w",
    "jpg": "/images/group/statement-640.jpg 640w, /images/group/statement-1024.jpg 1024w, /images/group/statement-1440.jpg 1440w, /images/group/statement-2000.jpg 2000w",
    "fallback": "/images/group/statement-1024.jpg",
    "duotone": {
      "lqip": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADQAwCdASoYABAAPu1iqU2ppaOiMAgBMB2JaQAAW+wSP8WBzs805wAA/vC9TwOjBZcoL/X1eaF7xmkHAydf3ifOgl2cQxRQO307OdPhRrDoBfExy7tXPoXSqug6FSAA",
      "webp": "/images/group/statement-duotone-640.webp 640w, /images/group/statement-duotone-1024.webp 1024w, /images/group/statement-duotone-1440.webp 1440w, /images/group/statement-duotone-2000.webp 2000w",
      "jpg": "/images/group/statement-duotone-640.jpg 640w, /images/group/statement-duotone-1024.jpg 1024w, /images/group/statement-duotone-1440.jpg 1440w, /images/group/statement-duotone-2000.jpg 2000w",
      "fallback": "/images/group/statement-duotone-1024.jpg"
    }
  },
  "/images/group/story.jpg": {
    "w": 5502,
    "h": 8033,
    "lqip": "data:image/webp;base64,UklGRgABAABXRUJQVlA4IPQAAACwBgCdASoYACMAPu1oq1AppaOiqrgMATAdiWMAt0MzgbJygBbW46Q+hsWpuadVeO5ve8hcIgfEYeKU7YV7oAD+22H5tTqfCSDJyPfIBH7jqH9QyqePLKF1/N9+qk/8A7yWjSd4UeXzfr/uLe1XfKYExxy/jhhRlVsbc16EnXPHsTGBMufXuqaXP24a/qOQUQDcHQukg4wE/nIg9R4r2gRtZHvxZEEsllju9Vsyel2Kl0lhuKYzmIXvnCCFxHDB1ljrKJH3OSkWXNyGkdiIA0AKJJ369vVkcZBpb20NvAZiZ2Qu2zWYJXv3MrqHDUJthixCBu4A",
    "webp": "/images/group/story-420.webp 420w, /images/group/story-768.webp 768w, /images/group/story-1100.webp 1100w, /images/group/story-1520.webp 1520w",
    "jpg": "/images/group/story-420.jpg 420w, /images/group/story-768.jpg 768w, /images/group/story-1100.jpg 1100w, /images/group/story-1520.jpg 1520w",
    "fallback": "/images/group/story-1100.jpg"
  },
  "/images/group/structure.jpg": {
    "w": 7680,
    "h": 4320,
    "lqip": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAADwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JagC7MoAB38kWQwn+NT1gAP6DgvuYJT9sGsVPZlGWodQy4sRwwfJO0Y1WssXB/7tkuu6GC5roSZmNBgVVuk3KWe4M/AZbTzNNOtaVMUqrbSL8pLkc1f4574Gc0Krq9Va+JoVGVT/YkgTI8AA=",
    "webp": "/images/group/structure-420.webp 420w, /images/group/structure-768.webp 768w, /images/group/structure-1100.webp 1100w, /images/group/structure-1520.webp 1520w",
    "jpg": "/images/group/structure-420.jpg 420w, /images/group/structure-768.jpg 768w, /images/group/structure-1100.jpg 1100w, /images/group/structure-1520.jpg 1520w",
    "fallback": "/images/group/structure-1100.jpg"
  },
  "/images/group/texture.jpg": {
    "w": 1200,
    "h": 1200,
    "lqip": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAACQBACdASoYABgAPu1urU2pp6SiMAgBMB2JaQDNwGlfuBK2IgQTb81CQkZshAAA/tNuR3E0uV9IRN/8+EDrch8ttd2g7O6RRuA/IY6/iZt+E9lRMSQdSDxGcZMfymbL/YAAAA==",
    "webp": "/images/group/texture-420.webp 420w, /images/group/texture-768.webp 768w, /images/group/texture-1100.webp 1100w, /images/group/texture-1200.webp 1200w",
    "jpg": "/images/group/texture-420.jpg 420w, /images/group/texture-768.jpg 768w, /images/group/texture-1100.jpg 1100w, /images/group/texture-1200.jpg 1200w",
    "fallback": "/images/group/texture-1100.jpg"
  },
  "/images/group/values.jpg": {
    "w": 2000,
    "h": 1125,
    "lqip": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAABQBACdASoYAA0APu1iqU2ppaOiMAgBMB2JZwCnFywBz17uFq7UbVAxNdNAAPhbLpkvETVDvbzVoI7Yq3sSg/hiAN/hM6V89kjKRyt3Zh2QoDFPTU86cQMrhQKgpA3DBQGgP+epjgA=",
    "webp": "/images/group/values-420.webp 420w, /images/group/values-768.webp 768w, /images/group/values-1100.webp 1100w, /images/group/values-1520.webp 1520w",
    "jpg": "/images/group/values-420.jpg 420w, /images/group/values-768.jpg 768w, /images/group/values-1100.jpg 1100w, /images/group/values-1520.jpg 1520w",
    "fallback": "/images/group/values-1100.jpg"
  },
  "/images/properties/detail.jpg": {
    "w": 5640,
    "h": 3764,
    "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACQAwCdASoYABAAPu1iqU2ppaOiMAgBMB2JQBOmUACMzwJ2PKkAAP7sOrkMTo3R9U/i9lyrOlMOczzNCT8xzGKwTY//mve/Ly2gmgAA",
    "webp": "/images/properties/detail-420.webp 420w, /images/properties/detail-768.webp 768w, /images/properties/detail-1100.webp 1100w, /images/properties/detail-1520.webp 1520w",
    "jpg": "/images/properties/detail-420.jpg 420w, /images/properties/detail-768.jpg 768w, /images/properties/detail-1100.jpg 1100w, /images/properties/detail-1520.jpg 1520w",
    "fallback": "/images/properties/detail-1100.jpg"
  },
  "/images/properties/development-team.jpg": {
    "w": 5130,
    "h": 3420,
    "lqip": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAABQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JbACdMoAC2/scpf9tcWzbAFmYAP7QwZf5pl8z754Uk8jF5tx6EhU2hw7clfbesW/Bo9uQqxca6jj2182hLOXNfFGE0tK6lVgtmnxR82CspcN5vb9YXfwbfjnDT/fZc8s86K7wP3uIgF4mnYgDyzmZoToScVNpuqjxXkDw7COMqH3ra7BVs2H0/lPF25+nBz/3CwAA",
    "webp": "/images/properties/development-team-420.webp 420w, /images/properties/development-team-768.webp 768w, /images/properties/development-team-1100.webp 1100w, /images/properties/development-team-1520.webp 1520w",
    "jpg": "/images/properties/development-team-420.jpg 420w, /images/properties/development-team-768.jpg 768w, /images/properties/development-team-1100.jpg 1100w, /images/properties/development-team-1520.jpg 1520w",
    "fallback": "/images/properties/development-team-1100.jpg"
  },
  "/images/properties/development.jpg": {
    "w": 1500,
    "h": 1000,
    "lqip": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAABwBACdASoYABAAPu1mq04ppaQiMAgBMB2JbACdMoR3AH4ZC/BPkYb2UTvXTAD90UN0KvDeVsCdibk8xEkV/h+TyypYvEY6M74H/xvEzKnhSWsn/no2xP/t39v+Hmf389iUUZALg/6+xG+Al8//kmQgT50CUAoLLtApZGseungGhZfRwrc8CakW92l/NQNrsNm8GAAA",
    "webp": "/images/properties/development-420.webp 420w, /images/properties/development-768.webp 768w, /images/properties/development-1100.webp 1100w, /images/properties/development-1500.webp 1500w",
    "jpg": "/images/properties/development-420.jpg 420w, /images/properties/development-768.jpg 768w, /images/properties/development-1100.jpg 1100w, /images/properties/development-1500.jpg 1500w",
    "fallback": "/images/properties/development-1100.jpg"
  },
  "/images/properties/duotone.jpg": {
    "w": 2000,
    "h": 1125,
    "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACQAwCdASoYAA0APu1mq04ppaQiMAgBMB2JZwC06BP2RCwqLxAAAPnWgDXvkJTme8fWrjXeBKL9SWY4qorNhNOBGo9/O59NYfH+f3gz3A7AAA==",
    "webp": "/images/properties/duotone-420.webp 420w, /images/properties/duotone-768.webp 768w, /images/properties/duotone-1100.webp 1100w, /images/properties/duotone-1520.webp 1520w",
    "jpg": "/images/properties/duotone-420.jpg 420w, /images/properties/duotone-768.jpg 768w, /images/properties/duotone-1100.jpg 1100w, /images/properties/duotone-1520.jpg 1520w",
    "fallback": "/images/properties/duotone-1100.jpg"
  },
  "/images/properties/hero.jpg": {
    "w": 6144,
    "h": 4044,
    "lqip": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAADQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JbACdMoMYA0kBlWGAADaR5q83Wv1kQAD+7uY3c+nqCbw/oIf2RRNSEtCjKL3JGjN6XtcXj72zJ+PxBUvbgU1zMaqlmhRHl9/AnBRw/O042IIBxJPThV14RnnnX2dPr7oVW2yd3/yiXWjRsWsAgit9K4IsqpBcmRVzndC9SxLFFlntlOuyfAY1lWiybZkQPAA=",
    "webp": "/images/properties/hero-640.webp 640w, /images/properties/hero-1024.webp 1024w, /images/properties/hero-1440.webp 1440w, /images/properties/hero-2000.webp 2000w",
    "jpg": "/images/properties/hero-640.jpg 640w, /images/properties/hero-1024.jpg 1024w, /images/properties/hero-1440.jpg 1440w, /images/properties/hero-2000.jpg 2000w",
    "fallback": "/images/properties/hero-1024.jpg"
  },
  "/images/properties/lifestyle.jpg": {
    "w": 6000,
    "h": 4000,
    "lqip": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAABQBACdASoYABAAPu1kqU2ppaOiMAgBMB2JQBYd5YA2f/pgZ6EyCuUHaXiAAP7yofvCsZ6fpgAbd0JlOFSJKbWRgvI3lN10YXHdgXukNXFwXJb5xnY9t2vf3D6gRq8AdBI9B6NPuxDTr1936rm8+K2AYD38tA6VjSgYAAAA",
    "webp": "/images/properties/lifestyle-420.webp 420w, /images/properties/lifestyle-768.webp 768w, /images/properties/lifestyle-1100.webp 1100w, /images/properties/lifestyle-1520.webp 1520w",
    "jpg": "/images/properties/lifestyle-420.jpg 420w, /images/properties/lifestyle-768.jpg 768w, /images/properties/lifestyle-1100.jpg 1100w, /images/properties/lifestyle-1520.jpg 1520w",
    "fallback": "/images/properties/lifestyle-1100.jpg"
  },
  "/images/properties/real-estate.jpg": {
    "w": 3687,
    "h": 5531,
    "lqip": "data:image/webp;base64,UklGRsgAAABXRUJQVlA4ILwAAACwBgCdASoYACQAPu1qrVEppaQiqrgKATAdiWMAs7OwBPVqDA8o/WDdEPez3/vLYq2DpPwbxq0RrjPjuQJCAACpKD56IUaLwjQ4vVicD71ovRU8e7awd0Cu3q2jcv5UwZG5MeX/cPf31Loo41hyNQa4iZWCTHcIxCmskIwvGjWPFXBj3t08wYNKab/WLEAL2u5SPkLb4/hvwL480a4GTgRKa9qP1Vx2Sz4bVu2p+0wFERegBXw9lZk8eykAAA==",
    "webp": "/images/properties/real-estate-420.webp 420w, /images/properties/real-estate-768.webp 768w, /images/properties/real-estate-1100.webp 1100w, /images/properties/real-estate-1520.webp 1520w",
    "jpg": "/images/properties/real-estate-420.jpg 420w, /images/properties/real-estate-768.jpg 768w, /images/properties/real-estate-1100.jpg 1100w, /images/properties/real-estate-1520.jpg 1520w",
    "fallback": "/images/properties/real-estate-1100.jpg"
  },
  "/images/properties/statement.jpg": {
    "w": 7008,
    "h": 4672,
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAABwBACdASoYABAAPu1iqU2ppaQiMAgBMB2JQBOmUI7gBTLkvz1xgk+hwjhVgAD+r20r12jrEh/4SustxL5N8Nb5WwnqWTZGFwe5YJHcbfoPRkXMAAA=",
    "webp": "/images/properties/statement-640.webp 640w, /images/properties/statement-1024.webp 1024w, /images/properties/statement-1440.webp 1440w, /images/properties/statement-2000.webp 2000w",
    "jpg": "/images/properties/statement-640.jpg 640w, /images/properties/statement-1024.jpg 1024w, /images/properties/statement-1440.jpg 1440w, /images/properties/statement-2000.jpg 2000w",
    "fallback": "/images/properties/statement-1024.jpg",
    "duotone": {
      "lqip": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAQBACdASoYABAAPu1kqU2ppaQiMAgBMB2JaQAAUwzcLd85+dlBDCN8gAD+r5sSNyvDrukPCS6NpxBfYKyu1zsJ3wCiZF0AAAA=",
      "webp": "/images/properties/statement-duotone-640.webp 640w, /images/properties/statement-duotone-1024.webp 1024w, /images/properties/statement-duotone-1440.webp 1440w, /images/properties/statement-duotone-2000.webp 2000w",
      "jpg": "/images/properties/statement-duotone-640.jpg 640w, /images/properties/statement-duotone-1024.jpg 1024w, /images/properties/statement-duotone-1440.jpg 1440w, /images/properties/statement-duotone-2000.jpg 2000w",
      "fallback": "/images/properties/statement-duotone-1024.jpg"
    }
  },
  "/images/properties/stay.jpg": {
    "w": 3899,
    "h": 5646,
    "lqip": "data:image/webp;base64,UklGRuoAAABXRUJQVlA4IN4AAACQBQCdASoYACMAPu1srE8ppqQiKrgMATAdiWMAw3Ah8JrgWdovaO/srNitXg10Yw0QqmOwAAD1/uexc0bgMUTsuGOJp28NnTP3jDwTOXHkqiOKh+MxnYBd4rDslcKGevbkWVSOwwgud1DZFXqqncX9SjTsooZcwmH50+olTupJfGdUKDLdmzCw8zF+H4rBhqWTEJxA+HSZ4Scr9/vVIaZU3kemUBsmxY8ea83rZGyU+w7+VDnYQCpAw4f7QRrbjkKP55UJi1Ifx8KIXhFpv+/ZOX1ESdKZQf1dpDf6AAA=",
    "webp": "/images/properties/stay-420.webp 420w, /images/properties/stay-768.webp 768w, /images/properties/stay-1100.webp 1100w, /images/properties/stay-1520.webp 1520w",
    "jpg": "/images/properties/stay-420.jpg 420w, /images/properties/stay-768.jpg 768w, /images/properties/stay-1100.jpg 1100w, /images/properties/stay-1520.jpg 1520w",
    "fallback": "/images/properties/stay-1100.jpg"
  },
  "/images/sunab/fibre-operations.jpg": {
    "w": 5660,
    "h": 3778,
    "lqip": "data:image/webp;base64,UklGRtAAAABXRUJQVlA4IMQAAABQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZACdAq/5yYO2bj5CP0c49Y4AAM490yyNE3qCxBoppuCsUegicMYm5PHTidjEClRbu/vIAfnV4VKmZCJtUZVVr0KC1rfQZj8ITEO+PY3uptUafop63Lq6qOsK4miLZ4n60C7N6PqlVtPF/XKclwUs3uRB+V1K7y3vATP6pK/+gAxwzBVyV/I2fdQiAFsyMKfR6vfd8X+qDSjFiXvMnEf7q2fg/Mhc7NJAYXAA",
    "webp": "/images/sunab/fibre-operations-420.webp 420w, /images/sunab/fibre-operations-768.webp 768w, /images/sunab/fibre-operations-1100.webp 1100w, /images/sunab/fibre-operations-1520.webp 1520w",
    "jpg": "/images/sunab/fibre-operations-420.jpg 420w, /images/sunab/fibre-operations-768.jpg 768w, /images/sunab/fibre-operations-1100.jpg 1100w, /images/sunab/fibre-operations-1520.jpg 1520w",
    "fallback": "/images/sunab/fibre-operations-1100.jpg"
  },
  "/images/sunab/field-engineer.jpg": {
    "w": 1376,
    "h": 768,
    "lqip": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAADwAwCdASoYAA0APu1iqU2ppaOiMAgBMB2JYwCACDAAfg4URL3dmygAAP7I94nY+vMWFxdShQJZhltK4Pi39fsOWMhaBhAdg6AYFBkP7iOE39osJ1odqAibaEs+FxGM2Hsxt9DaAElHHXbkJxQBsPCSON3Tt+/L6gtbC+Ffv34yqEsvR9gKty45BSRtElAlSTAAgeToKBaNOSuwbOIsGUqg8AAAAA==",
    "webp": "/images/sunab/field-engineer-420.webp 420w, /images/sunab/field-engineer-768.webp 768w, /images/sunab/field-engineer-1100.webp 1100w, /images/sunab/field-engineer-1376.webp 1376w",
    "jpg": "/images/sunab/field-engineer-420.jpg 420w, /images/sunab/field-engineer-768.jpg 768w, /images/sunab/field-engineer-1100.jpg 1100w, /images/sunab/field-engineer-1376.jpg 1376w",
    "fallback": "/images/sunab/field-engineer-1100.jpg"
  },
  "/images/sunab/hero.jpg": {
    "w": 3840,
    "h": 2160,
    "lqip": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAABwBACdASoYAA4APu1kqU2ppaOiMAgBMB2JQBOmUGMEz/gQF4uuR7ru9q4GAAD+2mzJRTx05sknZVqL8BejnNwj0q3a8lHb7cR3NGr8DAkWCMorKN6Ss/P+vpymNp++jH7RhXMlKD90MegLaiPA+EAAAAA=",
    "webp": "/images/sunab/hero-640.webp 640w, /images/sunab/hero-1024.webp 1024w, /images/sunab/hero-1440.webp 1440w, /images/sunab/hero-2000.webp 2000w",
    "jpg": "/images/sunab/hero-640.jpg 640w, /images/sunab/hero-1024.jpg 1024w, /images/sunab/hero-1440.jpg 1440w, /images/sunab/hero-2000.jpg 2000w",
    "fallback": "/images/sunab/hero-1024.jpg"
  },
  "/images/sunab/infrastructure.jpg": {
    "w": 5743,
    "h": 3829,
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAACwAwCdASoYABAAPu1iqU2ppaOiMAgBMB2JagCdMoADQw8qNO+IAAD+8NRWJjcFV3j8LD2p3ZAOVoLQhUwJRrEuv9foJqvMBqYzBdtwFTw3EQrpFsPcmxR0XNZAAA==",
    "webp": "/images/sunab/infrastructure-420.webp 420w, /images/sunab/infrastructure-768.webp 768w, /images/sunab/infrastructure-1100.webp 1100w, /images/sunab/infrastructure-1520.webp 1520w",
    "jpg": "/images/sunab/infrastructure-420.jpg 420w, /images/sunab/infrastructure-768.jpg 768w, /images/sunab/infrastructure-1100.jpg 1100w, /images/sunab/infrastructure-1520.jpg 1520w",
    "fallback": "/images/sunab/infrastructure-1100.jpg"
  },
  "/images/sunab/network-operations.jpg": {
    "w": 2560,
    "h": 1440,
    "lqip": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAADQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JbACdMoRwA8ABsdsp/g6Cys1892cDwAD7+bVhnPAVZnHGthPFcvMGin1eWzUqUYy3tx2/Q/T4xPHrvoA4lAxYOSMcx+9325ro18eiIF3dl0ve//LNmNXADvgQ1U4PFhAqXIrKvQF0NcatplcTCxUbr99YzxOhfyFB8kUZGBpV4Oz++JUaBjfvYIAXUAW/TaFYAAAA",
    "webp": "/images/sunab/network-operations-420.webp 420w, /images/sunab/network-operations-768.webp 768w, /images/sunab/network-operations-1100.webp 1100w, /images/sunab/network-operations-1520.webp 1520w",
    "jpg": "/images/sunab/network-operations-420.jpg 420w, /images/sunab/network-operations-768.jpg 768w, /images/sunab/network-operations-1100.jpg 1100w, /images/sunab/network-operations-1520.jpg 1520w",
    "fallback": "/images/sunab/network-operations-1100.jpg"
  },
  "/images/sunab/network.jpg": {
    "w": 4240,
    "h": 2827,
    "lqip": "data:image/webp;base64,UklGRtoAAABXRUJQVlA4IM4AAACQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JbACdMoMYA0bmADTUrQxWtQLS7bAA/PYmV9qN6VIcUEzD6Sq/4UKQu67sLOnQJFKdFGAFGgWrygL05t7ElhY8qBmXeP2/Zkbe77E65+8H1K26nPUrpISsS6NxD961yI8pCwv/23yRqhr6zrBfUYP3VO0gUvuktaOKtoFoLb5ep203Bu4gdEtW/IL1EBaXzelapbQcAVqiNUe3HH4CA9XvqvCIp+i3cdqG3QnBVLpxHdEIG1BAAA==",
    "webp": "/images/sunab/network-420.webp 420w, /images/sunab/network-768.webp 768w, /images/sunab/network-1100.webp 1100w, /images/sunab/network-1520.webp 1520w",
    "jpg": "/images/sunab/network-420.jpg 420w, /images/sunab/network-768.jpg 768w, /images/sunab/network-1100.jpg 1100w, /images/sunab/network-1520.jpg 1520w",
    "fallback": "/images/sunab/network-1100.jpg"
  },
  "/images/sunab/statement.jpg": {
    "w": 5616,
    "h": 3744,
    "lqip": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAABwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JbACdMoGv/gL9eB/HTpvzJ6KNgAD+3a/TGNiRp+mmT9CAew8ANQ2ZTnH+pFOiagccf4FQBypth1IDFum1tzJZoX5ePBWRscxFNp9GEO1unW6/RcrUqljgzmPE/nLC9T2NDM7z+diCqDUmyXAVreOq22GqaW2yHYDoLkW5l9sel2fIK3kOP3bMECvVAAAA",
    "webp": "/images/sunab/statement-640.webp 640w, /images/sunab/statement-1024.webp 1024w, /images/sunab/statement-1440.webp 1440w, /images/sunab/statement-2000.webp 2000w",
    "jpg": "/images/sunab/statement-640.jpg 640w, /images/sunab/statement-1024.jpg 1024w, /images/sunab/statement-1440.jpg 1440w, /images/sunab/statement-2000.jpg 2000w",
    "fallback": "/images/sunab/statement-1024.jpg",
    "duotone": {
      "lqip": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAADQAwCdASoYABAAPu1iqU2ppaOiMAgBMB2JaQAAWpYcrxseJ1n70wAA/sHLZyMGHAJOv7eGSYSLRCSOa9JF0Bo9Xuta0VHewP6fPPyPGFi3NZiksx3uETSpdsvbns5jxPssBsfV1bYLXQ+haW/D/4Wn80QDOneJXY+XlTB67+mzX9+OCIAAAA==",
      "webp": "/images/sunab/statement-duotone-640.webp 640w, /images/sunab/statement-duotone-1024.webp 1024w, /images/sunab/statement-duotone-1440.webp 1440w, /images/sunab/statement-duotone-2000.webp 2000w",
      "jpg": "/images/sunab/statement-duotone-640.jpg 640w, /images/sunab/statement-duotone-1024.jpg 1024w, /images/sunab/statement-duotone-1440.jpg 1440w, /images/sunab/statement-duotone-2000.jpg 2000w",
      "fallback": "/images/sunab/statement-duotone-1024.jpg"
    }
  },
  "/images/tishino/agronomy.jpg": {
    "w": 6720,
    "h": 4480,
    "lqip": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAACQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JbACdMoBnArYhUWg0kGHPHcWrj0AA/YUjGub9z8UR+pc/qBIyj78Fi0S7xevX2AWgr1jvQP6frzQqmABOV2zTjzQKU+nz5GuqsRcyG/UDDYIOjra93sTVjVaw8/YBglywLX/u+BPHK7E2AlTTuiSiuEx5Mq8GFumDwAAA",
    "webp": "/images/tishino/agronomy-420.webp 420w, /images/tishino/agronomy-768.webp 768w, /images/tishino/agronomy-1100.webp 1100w, /images/tishino/agronomy-1520.webp 1520w",
    "jpg": "/images/tishino/agronomy-420.jpg 420w, /images/tishino/agronomy-768.jpg 768w, /images/tishino/agronomy-1100.jpg 1100w, /images/tishino/agronomy-1520.jpg 1520w",
    "fallback": "/images/tishino/agronomy-1100.jpg"
  },
  "/images/tishino/beans.jpg": {
    "w": 6123,
    "h": 8164,
    "lqip": "data:image/webp;base64,UklGRkYBAABXRUJQVlA4IDoBAABQBwCdASoYACAAPu1sqk8ppiOiMBgIATAdiWwAgUQwGzbslWsS4xGW7Z8I7/JcIdMingIQgmTEXNrwJJbkKYJMwqfAAP7wn172uiwZ2I+f+MjwNrvnE4S4TuR/+MBvoiLqQOd9sEjSMYhMVnhrFfnPP5MWGu1X2PFuCJBNJRT29zQdgYV2/9EBVRWbkS6uiGOEm8UZ1uOLKLF+Iln8kNpeBNmvf5FfLIuKINJWincH/rb/WTvRabh0OIW633E58b0gd6KDiPMNQ4/6y5Wki+wxtyogTDhI9SxdWH+TMynhOrrnssqqBD/fO4SPI26bsSpHOI+4eu8jQY3oENYBlSfsl57bx2kn1b3fNStS0ahaNd8yz9kGrTOC+5k6CTTDTxblDoUQoUP+W4GjZvV0rPBrkyHVNH/bMcAAAA==",
    "webp": "/images/tishino/beans-420.webp 420w, /images/tishino/beans-768.webp 768w, /images/tishino/beans-1100.webp 1100w, /images/tishino/beans-1520.webp 1520w",
    "jpg": "/images/tishino/beans-420.jpg 420w, /images/tishino/beans-768.jpg 768w, /images/tishino/beans-1100.jpg 1100w, /images/tishino/beans-1520.jpg 1520w",
    "fallback": "/images/tishino/beans-1100.jpg"
  },
  "/images/tishino/distribution.jpg": {
    "w": 5651,
    "h": 3737,
    "lqip": "data:image/webp;base64,UklGRswAAABXRUJQVlA4IMAAAADwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JQBjihswXgy7wGc2oXnhHZdUcF+a43gAA/ueglHu3i/EbBWjWz2P1e2oqJrmTVZ8PWK5pnDndFkVcTM3fPsJLYS60n5jFwUxdPoSQKwNkc0Iwe5427VfjnUwkmX9o8LAcwBkb6Sh4RLukhinV/8yXPhIm00GtuS4SsI+xtJ9M8ElZgKyGqm1yY45F2exUKMOoedgO6Gtl1CIr1dYUQII8OzaBGgOoAAA=",
    "webp": "/images/tishino/distribution-420.webp 420w, /images/tishino/distribution-768.webp 768w, /images/tishino/distribution-1100.webp 1100w, /images/tishino/distribution-1520.webp 1520w",
    "jpg": "/images/tishino/distribution-420.jpg 420w, /images/tishino/distribution-768.jpg 768w, /images/tishino/distribution-1100.jpg 1100w, /images/tishino/distribution-1520.jpg 1520w",
    "fallback": "/images/tishino/distribution-1100.jpg"
  },
  "/images/tishino/hero.jpg": {
    "w": 8256,
    "h": 5504,
    "lqip": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAABwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JagCsIMgCu8GXUt7TLkRrzV2+9AD+62CSF80g0G5Mm/oJC8JyV8DpPHPrk12YbruvKfCV0udaitajjKusj2PBWfLV8BJtbDHlExuTR+YjHFWkkYA6JS5dzNiebtLS9VJEYB4t0wAKXggfiB4jUtzInQAAAA==",
    "webp": "/images/tishino/hero-640.webp 640w, /images/tishino/hero-1024.webp 1024w, /images/tishino/hero-1440.webp 1440w, /images/tishino/hero-2000.webp 2000w",
    "jpg": "/images/tishino/hero-640.jpg 640w, /images/tishino/hero-1024.jpg 1024w, /images/tishino/hero-1440.jpg 1440w, /images/tishino/hero-2000.jpg 2000w",
    "fallback": "/images/tishino/hero-1024.jpg"
  },
  "/images/tishino/maize.jpg": {
    "w": 1200,
    "h": 1200,
    "lqip": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAQBACdASoYABgAPu1erE2ppKSiMBgMATAdiWMAnQAQ76H5HRWtw0+0wAD+02bA8FVmPYUCXRTAoKD6Nui+5bS9UMTZua+hQ8KttTutX6/l2K3hzyWBVgUxllCgWueZizKXiOmQcAA=",
    "webp": "/images/tishino/maize-420.webp 420w, /images/tishino/maize-768.webp 768w, /images/tishino/maize-1100.webp 1100w, /images/tishino/maize-1200.webp 1200w",
    "jpg": "/images/tishino/maize-420.jpg 420w, /images/tishino/maize-768.jpg 768w, /images/tishino/maize-1100.jpg 1100w, /images/tishino/maize-1200.jpg 1200w",
    "fallback": "/images/tishino/maize-1100.jpg"
  },
  "/images/tishino/operations.jpg": {
    "w": 8164,
    "h": 6123,
    "lqip": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAAAwBQCdASoYABIAPu1kq06ppaQiKA1RMB2JQBYhL/wDMAvAjX7/1SZLvmyaE7XJBtSCAAD81dVHSC1Gc5t2bXjvrHcJu3dahnPQA/ymGReXi4MlQh7xbyo7wslh6/3qrz9vxzGeM20KBhuJxKpAjiH89HcAIsMnSaABSyKQfPthhjPcOwyrxFj+AAA=",
    "webp": "/images/tishino/operations-420.webp 420w, /images/tishino/operations-768.webp 768w, /images/tishino/operations-1100.webp 1100w, /images/tishino/operations-1520.webp 1520w",
    "jpg": "/images/tishino/operations-420.jpg 420w, /images/tishino/operations-768.jpg 768w, /images/tishino/operations-1100.jpg 1100w, /images/tishino/operations-1520.jpg 1520w",
    "fallback": "/images/tishino/operations-1100.jpg"
  },
  "/images/tishino/produce.jpg": {
    "w": 3712,
    "h": 5568,
    "lqip": "data:image/webp;base64,UklGRsIAAABXRUJQVlA4ILYAAADQBgCdASoYACQAPu1mq1CppSOisBVYATAdiUAWXZq3/oI8X6wDHO/R4KBH2OT3uR2LbPuM7M5fgI2981eVpAAA/u2Y8GXgPnIOxtIhT/Barccy8bpoESnORUA5Qjca3jyhNMX4xC7aE/iD6FAPyu38luyzlK/SvZyCewggLXlYGqwPepZ3WoW/gbdED4JoBQhxQbMKRYH46g5d/14qIN6mI92nx1Af7YBLnrpBE0SKhdfQFoAAAA==",
    "webp": "/images/tishino/produce-420.webp 420w, /images/tishino/produce-768.webp 768w, /images/tishino/produce-1100.webp 1100w, /images/tishino/produce-1520.webp 1520w",
    "jpg": "/images/tishino/produce-420.jpg 420w, /images/tishino/produce-768.jpg 768w, /images/tishino/produce-1100.jpg 1100w, /images/tishino/produce-1520.jpg 1520w",
    "fallback": "/images/tishino/produce-1100.jpg"
  },
  "/images/tishino/rice.jpg": {
    "w": 4640,
    "h": 6960,
    "lqip": "data:image/webp;base64,UklGRg4BAABXRUJQVlA4IAIBAACQBgCdASoYACQAPu1or1KppSQiqrgIATAdiWIArDNaPSJL1TIpPHZpiz//Kf8cBew/tJzo7TpaO2IckcfwAPcm0mJNjK+kmxZjT+7NDjyFmL2a9/cvJOoF6OOJ2L/G9WpvGjhtu1KfmY/lbFgHAgrbJ+Cv7/9QNJjsALAfDA9lg8WDf2NhzG7pAnMsJr9gC+l7N9uLpxH9FzRtDJELDZ6DPSFd7iobxyhEriOzcozzpTEolgCJd2fnIXnClwMZjUuhjG+RaJnppqBo/endHTdZm3M+KwBzSwmFEvS/T8AkQMKpD8qj9Hkc+QG4kc+XMd7apPJql/kORbE7dZuM7e7gAAA=",
    "webp": "/images/tishino/rice-420.webp 420w, /images/tishino/rice-768.webp 768w, /images/tishino/rice-1100.webp 1100w, /images/tishino/rice-1520.webp 1520w",
    "jpg": "/images/tishino/rice-420.jpg 420w, /images/tishino/rice-768.jpg 768w, /images/tishino/rice-1100.jpg 1100w, /images/tishino/rice-1520.jpg 1520w",
    "fallback": "/images/tishino/rice-1100.jpg"
  },
  "/images/tishino/roots-sorting.jpg": {
    "w": 1360,
    "h": 765,
    "lqip": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAABwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQBOgMXrS9lG9wgm9NNzxxnHGIADyV/xZvwfzhRCarQEtXrvh2+Ln/RyOP25AGGIol6XIZzPLTXABgZSzPHpJTKkWxtYcm119BltsNRmFW5/jYhnUjn56Ois09TE8d5BEWFGFq8J1PUFFDkQSfeiN0f2INegKYqqxOgZeN80497aCXRq6HJ2ALZrxA6nAAAA=",
    "webp": "/images/tishino/roots-sorting-420.webp 420w, /images/tishino/roots-sorting-768.webp 768w, /images/tishino/roots-sorting-1100.webp 1100w, /images/tishino/roots-sorting-1360.webp 1360w",
    "jpg": "/images/tishino/roots-sorting-420.jpg 420w, /images/tishino/roots-sorting-768.jpg 768w, /images/tishino/roots-sorting-1100.jpg 1100w, /images/tishino/roots-sorting-1360.jpg 1360w",
    "fallback": "/images/tishino/roots-sorting-1100.jpg"
  },
  "/images/tishino/staples.jpg": {
    "w": 3000,
    "h": 2008,
    "lqip": "data:image/webp;base64,UklGRtQAAABXRUJQVlA4IMgAAABwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JbACdMoMYJnbFr6nFWnI/Z94mAAD55iahN99ZRCESTxV5HyTkPpeqqehAaXBYeXuEfjo1R5SJxdulzCYZlEuL5CK7M7nhyvkOu0aE9NSxlep2g+vPPqtWvQDTiXM14Jmhx/BMa28GyMBX9GkLbuAA1bWumQAmViApESYOPybmkLAl0pd4KJFhjlG284+dgWNUROuVE5I425OkTPbcmmxrK4y5bC57h8X647/1Q2AAAA==",
    "webp": "/images/tishino/staples-420.webp 420w, /images/tishino/staples-768.webp 768w, /images/tishino/staples-1100.webp 1100w, /images/tishino/staples-1520.webp 1520w",
    "jpg": "/images/tishino/staples-420.jpg 420w, /images/tishino/staples-768.jpg 768w, /images/tishino/staples-1100.jpg 1100w, /images/tishino/staples-1520.jpg 1520w",
    "fallback": "/images/tishino/staples-1100.jpg"
  },
  "/images/tishino/statement.jpg": {
    "w": 4032,
    "h": 3024,
    "lqip": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAACwBACdASoYABIAPu1ip02ppaOiMAgBMB2JQBadA9C8cLeDnJwx5WwXI4r+TcsAAMqjpuWa03MNkY0asMZMNimh+DuideveXi0sFNdEOOwetU4Jx8E3lbERI6fJwhTyAAA=",
    "webp": "/images/tishino/statement-640.webp 640w, /images/tishino/statement-1024.webp 1024w, /images/tishino/statement-1440.webp 1440w, /images/tishino/statement-2000.webp 2000w",
    "jpg": "/images/tishino/statement-640.jpg 640w, /images/tishino/statement-1024.jpg 1024w, /images/tishino/statement-1440.jpg 1440w, /images/tishino/statement-2000.jpg 2000w",
    "fallback": "/images/tishino/statement-1024.jpg",
    "duotone": {
      "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAwBACdASoYABIAPuVepU2pJSOiMAwBIByJaQAAW9QE+EI/c8LCRR3oXAAAymyDfuMgzMwOeCgItqVzXVaA5cTcVh7RIo3hjQp8tJjiEDegAAAA",
      "webp": "/images/tishino/statement-duotone-640.webp 640w, /images/tishino/statement-duotone-1024.webp 1024w, /images/tishino/statement-duotone-1440.webp 1440w, /images/tishino/statement-duotone-2000.webp 2000w",
      "jpg": "/images/tishino/statement-duotone-640.jpg 640w, /images/tishino/statement-duotone-1024.jpg 1024w, /images/tishino/statement-duotone-1440.jpg 1440w, /images/tishino/statement-duotone-2000.jpg 2000w",
      "fallback": "/images/tishino/statement-duotone-1024.jpg"
    }
  },
  "/images/tishino/tubers.jpg": {
    "w": 6000,
    "h": 4000,
    "lqip": "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAABwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZACw7d0ZA9i7HZpiebZLV2m14AD9v5/CzmPtowktFZHEeLVA4IFRH5+1MJqQHuu5jvk7Ix/tR9ZsNcSNbn0hKLJpk3JBTtNB0480EEPRoPJ1xubrxwlXq8yreFz/pnywBxLXrQxR8wlAvuQZYYpz+FSy+pDP8D2LWN9MdlcA4GIRZd9x4RMzM0i1QytxqsPXKAEPiCAAAA==",
    "webp": "/images/tishino/tubers-420.webp 420w, /images/tishino/tubers-768.webp 768w, /images/tishino/tubers-1100.webp 1100w, /images/tishino/tubers-1520.webp 1520w",
    "jpg": "/images/tishino/tubers-420.jpg 420w, /images/tishino/tubers-768.jpg 768w, /images/tishino/tubers-1100.jpg 1100w, /images/tishino/tubers-1520.jpg 1520w",
    "fallback": "/images/tishino/tubers-1100.jpg"
  }
};
